import "./globals.css";
import NextAuthSessionProvider from "./libs/providers/sessionProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LoginModal from "./components/modal/LoginModal";
import RegisterModal from "./components/modal/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <RegisterModal />
          <LoginModal />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
